### ISSUE TITLE
Multiple Locks result in DeadLock

### ISSUE THREAD

**Issue by Callidus2000** [FriedrichWeinmann/Mutex#6]
Hi,
how to repeat the issue:
- issue `Lock-Mutex MyMutex` twice in one session
- issue `Lock-Mutex MyMutex` in another session, processing will halt
- issue `UnLock-Mutex MyMutex` in first session
- second process will not continue, has to be killed hard

**Comment by FriedrichWeinmann** [comment]
Can't repro - works just fine for me.
Can you give me a bit more specifics about your environment?

**Comment by Callidus2000** [comment]
Tested in 5.1 and 7.1.2, latest module version. Win10 1809 LTSC.
Any more information needed?

**Comment by Callidus2000** [comment]
![28-05-_2021_15-00-59](https://user-images.githubusercontent.com/73584079/119988196-23346c00-bfc6-11eb-8c02-59bde408da6c.png)

**Comment by FriedrichWeinmann** [comment]
Ah, alright, found the issue (and was able to repro).
Actually ... I uhm ... misread the original issue and missed the `twice` bit.

Found the issue, will be fixed this weekend.

**Comment by FriedrichWeinmann** [comment]
Alright, sorry about the delay, had a bit much going on, should be fixed with 1.1.9

**Comment by Callidus2000** [comment]
No problem the delay...
Funny, it is working manually... Tried to modify the Unlock-Mutex function to perform the unlocking multiple times if `LockCount -gt 1`. (https://github.com/FriedrichWeinmann/Mutex/commit/6a8a138d9803df55be3f22b7e51872207f18aeca) But that does not work while using in two processes. I have to unlock it manually a third time by calling '(Get-Mutex "Foo").Object.ReleaseMutex()', no idea why.....

Would it be a better aproach that `Lock-Mutex` checks if it is already locked and if yes dows not lock it again?

**Comment by Callidus2000** [comment]
Modified the approach in https://github.com/FriedrichWeinmann/Mutex/pull/8 by disregarding the LockCount in favor for releasing  in a loop until un-releasable (exception caught).

**Comment by FriedrichWeinmann** [comment]
Alright, should be resolved with 1.1.9 & 1.1.11, closing this for now
Thank you again for bringing this up and the contribution :)
